name: NTN

description: "A Flutter app for personal self-improvement, named NTN."
# Prevent accidental publishing
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^9.5.2
  intl: ^0.17.0
  flutter_localizations:
    sdk: flutter
  csv: ^5.0.0
  path_provider: ^2.0.11
  share_plus: ^6.3.0
  file_picker: ^5.2.2
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  intl_translation: ^0.17.10+1

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/